export type PartOfSpeech = 'noun' | 'verb' | 'adjective' | 'adverb' | 'preposition' | 'pronoun' | 'conjunction' | 'article' | 'numeral';

export interface Word {
  id: number;
  spanish: string;
  english: string;
  pos: PartOfSpeech;
  example: string;
  phonetic: string;
  tier: 1 | 2 | 3 | 4;
}

export const POS_COLORS: Record<PartOfSpeech, string> = {
  noun: '#60a5fa',       // blue
  verb: '#4ade80',       // green
  adjective: '#c084fc',  // purple
  adverb: '#facc15',     // yellow
  preposition: '#06b6d4',// cyan
  pronoun: '#818cf8',    // indigo
  conjunction: '#2dd4bf', // teal
  article: '#94a3b8',    // slate
  numeral: '#a78bfa',    // violet
};

export const vocabulary: Word[] = [
  // TIER 1: Top 50 most common
  { id: 1, spanish: "el", english: "the (m)", pos: "article", example: "El gato es negro.", phonetic: "el", tier: 1 },
  { id: 2, spanish: "la", english: "the (f)", pos: "article", example: "La casa es grande.", phonetic: "lah", tier: 1 },
  { id: 3, spanish: "de", english: "of / from", pos: "preposition", example: "Soy de México.", phonetic: "deh", tier: 1 },
  { id: 4, spanish: "que", english: "that / which", pos: "conjunction", example: "Creo que sí.", phonetic: "keh", tier: 1 },
  { id: 5, spanish: "y", english: "and", pos: "conjunction", example: "Tú y yo.", phonetic: "ee", tier: 1 },
  { id: 6, spanish: "en", english: "in / on", pos: "preposition", example: "Estoy en casa.", phonetic: "en", tier: 1 },
  { id: 7, spanish: "un", english: "a / an (m)", pos: "article", example: "Un libro nuevo.", phonetic: "oon", tier: 1 },
  { id: 8, spanish: "ser", english: "to be (permanent)", pos: "verb", example: "Yo soy estudiante.", phonetic: "sehr", tier: 1 },
  { id: 9, spanish: "se", english: "oneself", pos: "pronoun", example: "Se llama Juan.", phonetic: "seh", tier: 1 },
  { id: 10, spanish: "no", english: "no / not", pos: "adverb", example: "No quiero.", phonetic: "noh", tier: 1 },
  { id: 11, spanish: "haber", english: "to have (aux)", pos: "verb", example: "He comido.", phonetic: "ah-BEHR", tier: 1 },
  { id: 12, spanish: "por", english: "for / by", pos: "preposition", example: "Gracias por todo.", phonetic: "pohr", tier: 1 },
  { id: 13, spanish: "con", english: "with", pos: "preposition", example: "Café con leche.", phonetic: "kohn", tier: 1 },
  { id: 14, spanish: "su", english: "his/her/your", pos: "pronoun", example: "Su casa es bonita.", phonetic: "soo", tier: 1 },
  { id: 15, spanish: "para", english: "for / in order to", pos: "preposition", example: "Es para ti.", phonetic: "PAH-rah", tier: 1 },
  { id: 16, spanish: "como", english: "like / as / how", pos: "adverb", example: "¿Cómo estás?", phonetic: "KOH-moh", tier: 1 },
  { id: 17, spanish: "estar", english: "to be (temporary)", pos: "verb", example: "Estoy bien.", phonetic: "ehs-TAHR", tier: 1 },
  { id: 18, spanish: "tener", english: "to have", pos: "verb", example: "Tengo hambre.", phonetic: "teh-NEHR", tier: 1 },
  { id: 19, spanish: "le", english: "him/her (indirect)", pos: "pronoun", example: "Le doy el libro.", phonetic: "leh", tier: 1 },
  { id: 20, spanish: "lo", english: "it/him (direct)", pos: "pronoun", example: "Lo sé.", phonetic: "loh", tier: 1 },
  { id: 21, spanish: "todo", english: "all / everything", pos: "pronoun", example: "Todo está bien.", phonetic: "TOH-doh", tier: 1 },
  { id: 22, spanish: "pero", english: "but", pos: "conjunction", example: "Quiero, pero no puedo.", phonetic: "PEH-roh", tier: 1 },
  { id: 23, spanish: "más", english: "more / most", pos: "adverb", example: "Quiero más agua.", phonetic: "mahs", tier: 1 },
  { id: 24, spanish: "hacer", english: "to do / to make", pos: "verb", example: "¿Qué haces?", phonetic: "ah-SEHR", tier: 1 },
  { id: 25, spanish: "o", english: "or", pos: "conjunction", example: "¿Sí o no?", phonetic: "oh", tier: 1 },
  { id: 26, spanish: "poder", english: "to be able to", pos: "verb", example: "Puedo hacerlo.", phonetic: "poh-DEHR", tier: 1 },
  { id: 27, spanish: "decir", english: "to say / to tell", pos: "verb", example: "¿Qué dices?", phonetic: "deh-SEER", tier: 1 },
  { id: 28, spanish: "este", english: "this (m)", pos: "pronoun", example: "Este libro es mío.", phonetic: "EHS-teh", tier: 1 },
  { id: 29, spanish: "ir", english: "to go", pos: "verb", example: "Voy a la escuela.", phonetic: "eer", tier: 1 },
  { id: 30, spanish: "otro", english: "other / another", pos: "adjective", example: "Dame otro.", phonetic: "OH-troh", tier: 1 },
  { id: 31, spanish: "ese", english: "that (m)", pos: "pronoun", example: "Ese es mi amigo.", phonetic: "EH-seh", tier: 1 },
  { id: 32, spanish: "si", english: "if / yes", pos: "conjunction", example: "Si quieres, ven.", phonetic: "see", tier: 1 },
  { id: 33, spanish: "me", english: "me / myself", pos: "pronoun", example: "Me gusta.", phonetic: "meh", tier: 1 },
  { id: 34, spanish: "ya", english: "already / now", pos: "adverb", example: "Ya lo sé.", phonetic: "yah", tier: 1 },
  { id: 35, spanish: "ver", english: "to see", pos: "verb", example: "Puedo ver el mar.", phonetic: "behr", tier: 1 },
  { id: 36, spanish: "porque", english: "because", pos: "conjunction", example: "Porque te quiero.", phonetic: "pohr-KEH", tier: 1 },
  { id: 37, spanish: "dar", english: "to give", pos: "verb", example: "Dame agua.", phonetic: "dahr", tier: 1 },
  { id: 38, spanish: "cuando", english: "when", pos: "conjunction", example: "Cuando llueve.", phonetic: "KWAHN-doh", tier: 1 },
  { id: 39, spanish: "él", english: "he / him", pos: "pronoun", example: "Él es mi hermano.", phonetic: "ehl", tier: 1 },
  { id: 40, spanish: "muy", english: "very", pos: "adverb", example: "Muy bueno.", phonetic: "mooy", tier: 1 },
  { id: 41, spanish: "sin", english: "without", pos: "preposition", example: "Sin azúcar.", phonetic: "seen", tier: 1 },
  { id: 42, spanish: "tiempo", english: "time / weather", pos: "noun", example: "No tengo tiempo.", phonetic: "tee-EHM-poh", tier: 1 },
  { id: 43, spanish: "mismo", english: "same / self", pos: "adjective", example: "El mismo día.", phonetic: "MEES-moh", tier: 1 },
  { id: 44, spanish: "yo", english: "I", pos: "pronoun", example: "Yo quiero ir.", phonetic: "yoh", tier: 1 },
  { id: 45, spanish: "saber", english: "to know (facts)", pos: "verb", example: "Sé la respuesta.", phonetic: "sah-BEHR", tier: 1 },
  { id: 46, spanish: "ella", english: "she / her", pos: "pronoun", example: "Ella es doctora.", phonetic: "EH-yah", tier: 1 },
  { id: 47, spanish: "bien", english: "well / good", pos: "adverb", example: "Estoy bien.", phonetic: "bee-EHN", tier: 1 },
  { id: 48, spanish: "poco", english: "little / few", pos: "adjective", example: "Un poco de agua.", phonetic: "POH-koh", tier: 1 },
  { id: 49, spanish: "así", english: "like this / so", pos: "adverb", example: "Así es.", phonetic: "ah-SEE", tier: 1 },
  { id: 50, spanish: "grande", english: "big / large", pos: "adjective", example: "Una casa grande.", phonetic: "GRAHN-deh", tier: 1 },

  // TIER 2: 51-100
  { id: 51, spanish: "donde", english: "where", pos: "adverb", example: "¿Dónde vives?", phonetic: "DOHN-deh", tier: 2 },
  { id: 52, spanish: "año", english: "year", pos: "noun", example: "El año nuevo.", phonetic: "AH-nyoh", tier: 2 },
  { id: 53, spanish: "día", english: "day", pos: "noun", example: "Un buen día.", phonetic: "DEE-ah", tier: 2 },
  { id: 54, spanish: "mundo", english: "world", pos: "noun", example: "Todo el mundo.", phonetic: "MOON-doh", tier: 2 },
  { id: 55, spanish: "casa", english: "house", pos: "noun", example: "Mi casa es tu casa.", phonetic: "KAH-sah", tier: 2 },
  { id: 56, spanish: "país", english: "country", pos: "noun", example: "Este país es bonito.", phonetic: "pah-EES", tier: 2 },
  { id: 57, spanish: "parte", english: "part", pos: "noun", example: "La mejor parte.", phonetic: "PAHR-teh", tier: 2 },
  { id: 58, spanish: "vida", english: "life", pos: "noun", example: "La vida es bella.", phonetic: "BEE-dah", tier: 2 },
  { id: 59, spanish: "momento", english: "moment", pos: "noun", example: "Un momento, por favor.", phonetic: "moh-MEHN-toh", tier: 2 },
  { id: 60, spanish: "forma", english: "form / way", pos: "noun", example: "De esta forma.", phonetic: "FOHR-mah", tier: 2 },
  { id: 61, spanish: "nuevo", english: "new", pos: "adjective", example: "Un carro nuevo.", phonetic: "NWEH-boh", tier: 2 },
  { id: 62, spanish: "querer", english: "to want / to love", pos: "verb", example: "Te quiero mucho.", phonetic: "keh-REHR", tier: 2 },
  { id: 63, spanish: "hombre", english: "man", pos: "noun", example: "El hombre alto.", phonetic: "OHM-breh", tier: 2 },
  { id: 64, spanish: "mujer", english: "woman", pos: "noun", example: "La mujer fuerte.", phonetic: "moo-HEHR", tier: 2 },
  { id: 65, spanish: "llegar", english: "to arrive", pos: "verb", example: "Voy a llegar tarde.", phonetic: "yeh-GAHR", tier: 2 },
  { id: 66, spanish: "bueno", english: "good", pos: "adjective", example: "Es muy bueno.", phonetic: "BWEH-noh", tier: 2 },
  { id: 67, spanish: "primer", english: "first", pos: "adjective", example: "El primer día.", phonetic: "pree-MEHR", tier: 2 },
  { id: 68, spanish: "entre", english: "between / among", pos: "preposition", example: "Entre tú y yo.", phonetic: "EHN-treh", tier: 2 },
  { id: 69, spanish: "también", english: "also / too", pos: "adverb", example: "Yo también.", phonetic: "tahm-bee-EHN", tier: 2 },
  { id: 70, spanish: "gobierno", english: "government", pos: "noun", example: "El gobierno nuevo.", phonetic: "goh-bee-EHR-noh", tier: 2 },
  { id: 71, spanish: "hijo", english: "son / child", pos: "noun", example: "Mi hijo es joven.", phonetic: "EE-hoh", tier: 2 },
  { id: 72, spanish: "después", english: "after / later", pos: "adverb", example: "Después de comer.", phonetic: "dehs-PWEHS", tier: 2 },
  { id: 73, spanish: "cosa", english: "thing", pos: "noun", example: "Una cosa más.", phonetic: "KOH-sah", tier: 2 },
  { id: 74, spanish: "noche", english: "night", pos: "noun", example: "Buenas noches.", phonetic: "NOH-cheh", tier: 2 },
  { id: 75, spanish: "agua", english: "water", pos: "noun", example: "Quiero agua fría.", phonetic: "AH-gwah", tier: 2 },
  { id: 76, spanish: "menos", english: "less / minus", pos: "adverb", example: "Más o menos.", phonetic: "MEH-nohs", tier: 2 },
  { id: 77, spanish: "mejor", english: "better / best", pos: "adjective", example: "El mejor día.", phonetic: "meh-HOHR", tier: 2 },
  { id: 78, spanish: "encontrar", english: "to find", pos: "verb", example: "No puedo encontrar.", phonetic: "ehn-kohn-TRAHR", tier: 2 },
  { id: 79, spanish: "pensar", english: "to think", pos: "verb", example: "Pienso en ti.", phonetic: "pehn-SAHR", tier: 2 },
  { id: 80, spanish: "salir", english: "to leave / go out", pos: "verb", example: "Voy a salir.", phonetic: "sah-LEER", tier: 2 },
  { id: 81, spanish: "volver", english: "to return", pos: "verb", example: "Voy a volver.", phonetic: "bohl-BEHR", tier: 2 },
  { id: 82, spanish: "tomar", english: "to take / drink", pos: "verb", example: "Tomar un café.", phonetic: "toh-MAHR", tier: 2 },
  { id: 83, spanish: "conocer", english: "to know (people)", pos: "verb", example: "¿La conoces?", phonetic: "koh-noh-SEHR", tier: 2 },
  { id: 84, spanish: "sentir", english: "to feel", pos: "verb", example: "Me siento bien.", phonetic: "sehn-TEER", tier: 2 },
  { id: 85, spanish: "parecer", english: "to seem", pos: "verb", example: "Parece fácil.", phonetic: "pah-reh-SEHR", tier: 2 },
  { id: 86, spanish: "crear", english: "to create", pos: "verb", example: "Voy a crear algo.", phonetic: "kreh-AHR", tier: 2 },
  { id: 87, spanish: "hablar", english: "to speak / talk", pos: "verb", example: "Hablo español.", phonetic: "ah-BLAHR", tier: 2 },
  { id: 88, spanish: "llevar", english: "to carry / wear", pos: "verb", example: "Llevo una camisa.", phonetic: "yeh-BAHR", tier: 2 },
  { id: 89, spanish: "vivir", english: "to live", pos: "verb", example: "Vivo en España.", phonetic: "bee-BEER", tier: 2 },
  { id: 90, spanish: "trabajo", english: "work / job", pos: "noun", example: "Tengo mucho trabajo.", phonetic: "trah-BAH-hoh", tier: 2 },
  { id: 91, spanish: "comer", english: "to eat", pos: "verb", example: "Quiero comer.", phonetic: "koh-MEHR", tier: 2 },
  { id: 92, spanish: "escribir", english: "to write", pos: "verb", example: "Voy a escribir.", phonetic: "ehs-kree-BEER", tier: 2 },
  { id: 93, spanish: "leer", english: "to read", pos: "verb", example: "Me gusta leer.", phonetic: "leh-EHR", tier: 2 },
  { id: 94, spanish: "ciudad", english: "city", pos: "noun", example: "La ciudad grande.", phonetic: "see-oo-DAHD", tier: 2 },
  { id: 95, spanish: "niño", english: "boy / child", pos: "noun", example: "El niño juega.", phonetic: "NEE-nyoh", tier: 2 },
  { id: 96, spanish: "amigo", english: "friend", pos: "noun", example: "Mi mejor amigo.", phonetic: "ah-MEE-goh", tier: 2 },
  { id: 97, spanish: "nombre", english: "name", pos: "noun", example: "¿Cuál es tu nombre?", phonetic: "NOHM-breh", tier: 2 },
  { id: 98, spanish: "mano", english: "hand", pos: "noun", example: "Dame la mano.", phonetic: "MAH-noh", tier: 2 },
  { id: 99, spanish: "ejemplo", english: "example", pos: "noun", example: "Por ejemplo.", phonetic: "eh-HEHM-ploh", tier: 2 },
  { id: 100, spanish: "familia", english: "family", pos: "noun", example: "Mi familia es grande.", phonetic: "fah-MEE-lee-ah", tier: 2 },

  // TIER 3: 101-150
  { id: 101, spanish: "cabeza", english: "head", pos: "noun", example: "Me duele la cabeza.", phonetic: "kah-BEH-sah", tier: 3 },
  { id: 102, spanish: "ojo", english: "eye", pos: "noun", example: "Tiene ojos verdes.", phonetic: "OH-hoh", tier: 3 },
  { id: 103, spanish: "padre", english: "father", pos: "noun", example: "Mi padre cocina.", phonetic: "PAH-dreh", tier: 3 },
  { id: 104, spanish: "madre", english: "mother", pos: "noun", example: "Mi madre canta.", phonetic: "MAH-dreh", tier: 3 },
  { id: 105, spanish: "hermano", english: "brother", pos: "noun", example: "Mi hermano mayor.", phonetic: "ehr-MAH-noh", tier: 3 },
  { id: 106, spanish: "escuela", english: "school", pos: "noun", example: "Voy a la escuela.", phonetic: "ehs-KWEH-lah", tier: 3 },
  { id: 107, spanish: "libro", english: "book", pos: "noun", example: "Leo un libro.", phonetic: "LEE-broh", tier: 3 },
  { id: 108, spanish: "jugar", english: "to play", pos: "verb", example: "Quiero jugar.", phonetic: "hoo-GAHR", tier: 3 },
  { id: 109, spanish: "correr", english: "to run", pos: "verb", example: "Me gusta correr.", phonetic: "koh-REHR", tier: 3 },
  { id: 110, spanish: "dormir", english: "to sleep", pos: "verb", example: "Quiero dormir.", phonetic: "dohr-MEER", tier: 3 },
  { id: 111, spanish: "comida", english: "food / meal", pos: "noun", example: "La comida está rica.", phonetic: "koh-MEE-dah", tier: 3 },
  { id: 112, spanish: "perro", english: "dog", pos: "noun", example: "El perro ladra.", phonetic: "PEH-rroh", tier: 3 },
  { id: 113, spanish: "gato", english: "cat", pos: "noun", example: "El gato duerme.", phonetic: "GAH-toh", tier: 3 },
  { id: 114, spanish: "calle", english: "street", pos: "noun", example: "Camino por la calle.", phonetic: "KAH-yeh", tier: 3 },
  { id: 115, spanish: "dinero", english: "money", pos: "noun", example: "No tengo dinero.", phonetic: "dee-NEH-roh", tier: 3 },
  { id: 116, spanish: "puerta", english: "door", pos: "noun", example: "Abre la puerta.", phonetic: "PWEHR-tah", tier: 3 },
  { id: 117, spanish: "mesa", english: "table", pos: "noun", example: "En la mesa.", phonetic: "MEH-sah", tier: 3 },
  { id: 118, spanish: "sol", english: "sun", pos: "noun", example: "Brilla el sol.", phonetic: "sohl", tier: 3 },
  { id: 119, spanish: "luna", english: "moon", pos: "noun", example: "La luna llena.", phonetic: "LOO-nah", tier: 3 },
  { id: 120, spanish: "carro", english: "car", pos: "noun", example: "Tengo un carro.", phonetic: "KAH-rroh", tier: 3 },
  { id: 121, spanish: "rápido", english: "fast / quick", pos: "adjective", example: "El carro es rápido.", phonetic: "RRAH-pee-doh", tier: 3 },
  { id: 122, spanish: "lento", english: "slow", pos: "adjective", example: "Camina lento.", phonetic: "LEHN-toh", tier: 3 },
  { id: 123, spanish: "bonito", english: "pretty / nice", pos: "adjective", example: "Qué bonito.", phonetic: "boh-NEE-toh", tier: 3 },
  { id: 124, spanish: "feo", english: "ugly", pos: "adjective", example: "No es feo.", phonetic: "FEH-oh", tier: 3 },
  { id: 125, spanish: "alto", english: "tall / high", pos: "adjective", example: "Es muy alto.", phonetic: "AHL-toh", tier: 3 },
  { id: 126, spanish: "bajo", english: "short / low", pos: "adjective", example: "Es bajo.", phonetic: "BAH-hoh", tier: 3 },
  { id: 127, spanish: "caliente", english: "hot", pos: "adjective", example: "El café está caliente.", phonetic: "kah-lee-EHN-teh", tier: 3 },
  { id: 128, spanish: "frío", english: "cold", pos: "adjective", example: "Hace frío.", phonetic: "FREE-oh", tier: 3 },
  { id: 129, spanish: "número", english: "number", pos: "noun", example: "¿Cuál es tu número?", phonetic: "NOO-meh-roh", tier: 3 },
  { id: 130, spanish: "pregunta", english: "question", pos: "noun", example: "Tengo una pregunta.", phonetic: "preh-GOON-tah", tier: 3 },
  { id: 131, spanish: "respuesta", english: "answer", pos: "noun", example: "Sé la respuesta.", phonetic: "rehs-PWEHS-tah", tier: 3 },
  { id: 132, spanish: "palabra", english: "word", pos: "noun", example: "Una nueva palabra.", phonetic: "pah-LAH-brah", tier: 3 },
  { id: 133, spanish: "lado", english: "side", pos: "noun", example: "A mi lado.", phonetic: "LAH-doh", tier: 3 },
  { id: 134, spanish: "caminar", english: "to walk", pos: "verb", example: "Me gusta caminar.", phonetic: "kah-mee-NAHR", tier: 3 },
  { id: 135, spanish: "esperar", english: "to wait / hope", pos: "verb", example: "Espera un momento.", phonetic: "ehs-peh-RAHR", tier: 3 },
  { id: 136, spanish: "entender", english: "to understand", pos: "verb", example: "No entiendo.", phonetic: "ehn-tehn-DEHR", tier: 3 },
  { id: 137, spanish: "poner", english: "to put / place", pos: "verb", example: "Pon aquí.", phonetic: "poh-NEHR", tier: 3 },
  { id: 138, spanish: "llamar", english: "to call", pos: "verb", example: "Te voy a llamar.", phonetic: "yah-MAHR", tier: 3 },
  { id: 139, spanish: "creer", english: "to believe", pos: "verb", example: "Creo que sí.", phonetic: "kreh-EHR", tier: 3 },
  { id: 140, spanish: "seguir", english: "to follow / continue", pos: "verb", example: "Sigue adelante.", phonetic: "seh-GEER", tier: 3 },
  { id: 141, spanish: "contar", english: "to count / tell", pos: "verb", example: "Cuéntame todo.", phonetic: "kohn-TAHR", tier: 3 },
  { id: 142, spanish: "empezar", english: "to begin / start", pos: "verb", example: "Vamos a empezar.", phonetic: "ehm-peh-SAHR", tier: 3 },
  { id: 143, spanish: "pequeño", english: "small / little", pos: "adjective", example: "Un gato pequeño.", phonetic: "peh-KEH-nyoh", tier: 3 },
  { id: 144, spanish: "viejo", english: "old", pos: "adjective", example: "El hombre viejo.", phonetic: "bee-EH-hoh", tier: 3 },
  { id: 145, spanish: "joven", english: "young", pos: "adjective", example: "Es muy joven.", phonetic: "HOH-behn", tier: 3 },
  { id: 146, spanish: "fuerte", english: "strong", pos: "adjective", example: "Es muy fuerte.", phonetic: "FWEHR-teh", tier: 3 },
  { id: 147, spanish: "feliz", english: "happy", pos: "adjective", example: "Estoy feliz.", phonetic: "feh-LEES", tier: 3 },
  { id: 148, spanish: "triste", english: "sad", pos: "adjective", example: "Estoy triste.", phonetic: "TREES-teh", tier: 3 },
  { id: 149, spanish: "fácil", english: "easy", pos: "adjective", example: "Es fácil.", phonetic: "FAH-seel", tier: 3 },
  { id: 150, spanish: "difícil", english: "difficult", pos: "adjective", example: "Es difícil.", phonetic: "dee-FEE-seel", tier: 3 },

  // TIER 4: 151-200
  { id: 151, spanish: "cuerpo", english: "body", pos: "noun", example: "El cuerpo humano.", phonetic: "KWEHR-poh", tier: 4 },
  { id: 152, spanish: "corazón", english: "heart", pos: "noun", example: "Mi corazón late.", phonetic: "koh-rah-SOHN", tier: 4 },
  { id: 153, spanish: "tierra", english: "earth / land", pos: "noun", example: "La tierra fértil.", phonetic: "tee-EH-rrah", tier: 4 },
  { id: 154, spanish: "cielo", english: "sky / heaven", pos: "noun", example: "El cielo azul.", phonetic: "see-EH-loh", tier: 4 },
  { id: 155, spanish: "mar", english: "sea", pos: "noun", example: "El mar azul.", phonetic: "mahr", tier: 4 },
  { id: 156, spanish: "montaña", english: "mountain", pos: "noun", example: "La montaña alta.", phonetic: "mohn-TAH-nyah", tier: 4 },
  { id: 157, spanish: "árbol", english: "tree", pos: "noun", example: "Un árbol grande.", phonetic: "AHR-bohl", tier: 4 },
  { id: 158, spanish: "flor", english: "flower", pos: "noun", example: "Una flor bonita.", phonetic: "flohr", tier: 4 },
  { id: 159, spanish: "color", english: "color", pos: "noun", example: "¿De qué color?", phonetic: "koh-LOHR", tier: 4 },
  { id: 160, spanish: "blanco", english: "white", pos: "adjective", example: "El gato blanco.", phonetic: "BLAHN-koh", tier: 4 },
  { id: 161, spanish: "negro", english: "black", pos: "adjective", example: "El perro negro.", phonetic: "NEH-groh", tier: 4 },
  { id: 162, spanish: "azul", english: "blue", pos: "adjective", example: "El cielo azul.", phonetic: "ah-SOOL", tier: 4 },
  { id: 163, spanish: "verde", english: "green", pos: "adjective", example: "La hoja verde.", phonetic: "BEHR-deh", tier: 4 },
  { id: 164, spanish: "amarillo", english: "yellow", pos: "adjective", example: "El sol amarillo.", phonetic: "ah-mah-REE-yoh", tier: 4 },
  { id: 165, spanish: "cocina", english: "kitchen", pos: "noun", example: "Cocino en la cocina.", phonetic: "koh-SEE-nah", tier: 4 },
  { id: 166, spanish: "baño", english: "bathroom", pos: "noun", example: "¿Dónde está el baño?", phonetic: "BAH-nyoh", tier: 4 },
  { id: 167, spanish: "ventana", english: "window", pos: "noun", example: "Abre la ventana.", phonetic: "behn-TAH-nah", tier: 4 },
  { id: 168, spanish: "silla", english: "chair", pos: "noun", example: "Siéntate en la silla.", phonetic: "SEE-yah", tier: 4 },
  { id: 169, spanish: "cama", english: "bed", pos: "noun", example: "Voy a la cama.", phonetic: "KAH-mah", tier: 4 },
  { id: 170, spanish: "ropa", english: "clothes", pos: "noun", example: "La ropa limpia.", phonetic: "RROH-pah", tier: 4 },
  { id: 171, spanish: "zapato", english: "shoe", pos: "noun", example: "Mis zapatos nuevos.", phonetic: "sah-PAH-toh", tier: 4 },
  { id: 172, spanish: "camisa", english: "shirt", pos: "noun", example: "Una camisa azul.", phonetic: "kah-MEE-sah", tier: 4 },
  { id: 173, spanish: "aprender", english: "to learn", pos: "verb", example: "Quiero aprender.", phonetic: "ah-prehn-DEHR", tier: 4 },
  { id: 174, spanish: "enseñar", english: "to teach", pos: "verb", example: "Me gusta enseñar.", phonetic: "ehn-seh-NYAHR", tier: 4 },
  { id: 175, spanish: "comprar", english: "to buy", pos: "verb", example: "Voy a comprar.", phonetic: "kohm-PRAHR", tier: 4 },
  { id: 176, spanish: "vender", english: "to sell", pos: "verb", example: "Quiero vender.", phonetic: "behn-DEHR", tier: 4 },
  { id: 177, spanish: "abrir", english: "to open", pos: "verb", example: "Abre la puerta.", phonetic: "ah-BREER", tier: 4 },
  { id: 178, spanish: "cerrar", english: "to close", pos: "verb", example: "Cierra la puerta.", phonetic: "seh-RRAHR", tier: 4 },
  { id: 179, spanish: "cantar", english: "to sing", pos: "verb", example: "Me gusta cantar.", phonetic: "kahn-TAHR", tier: 4 },
  { id: 180, spanish: "bailar", english: "to dance", pos: "verb", example: "Quiero bailar.", phonetic: "bai-LAHR", tier: 4 },
  { id: 181, spanish: "cocinar", english: "to cook", pos: "verb", example: "Voy a cocinar.", phonetic: "koh-see-NAHR", tier: 4 },
  { id: 182, spanish: "ayudar", english: "to help", pos: "verb", example: "¿Puedes ayudar?", phonetic: "ah-yoo-DAHR", tier: 4 },
  { id: 183, spanish: "lunes", english: "Monday", pos: "noun", example: "Hoy es lunes.", phonetic: "LOO-nehs", tier: 4 },
  { id: 184, spanish: "martes", english: "Tuesday", pos: "noun", example: "Mañana es martes.", phonetic: "MAHR-tehs", tier: 4 },
  { id: 185, spanish: "miércoles", english: "Wednesday", pos: "noun", example: "El miércoles voy.", phonetic: "mee-EHR-koh-lehs", tier: 4 },
  { id: 186, spanish: "jueves", english: "Thursday", pos: "noun", example: "Nos vemos el jueves.", phonetic: "HWEH-behs", tier: 4 },
  { id: 187, spanish: "viernes", english: "Friday", pos: "noun", example: "¡Es viernes!", phonetic: "bee-EHR-nehs", tier: 4 },
  { id: 188, spanish: "uno", english: "one", pos: "numeral", example: "Solo uno.", phonetic: "OO-noh", tier: 4 },
  { id: 189, spanish: "dos", english: "two", pos: "numeral", example: "Tengo dos.", phonetic: "dohs", tier: 4 },
  { id: 190, spanish: "tres", english: "three", pos: "numeral", example: "Somos tres.", phonetic: "trehs", tier: 4 },
  { id: 191, spanish: "cuatro", english: "four", pos: "numeral", example: "Cuatro gatos.", phonetic: "KWAH-troh", tier: 4 },
  { id: 192, spanish: "cinco", english: "five", pos: "numeral", example: "Cinco dedos.", phonetic: "SEEN-koh", tier: 4 },
  { id: 193, spanish: "diez", english: "ten", pos: "numeral", example: "Diez minutos.", phonetic: "dee-EHS", tier: 4 },
  { id: 194, spanish: "cien", english: "one hundred", pos: "numeral", example: "Cien por ciento.", phonetic: "see-EHN", tier: 4 },
  { id: 195, spanish: "hoy", english: "today", pos: "adverb", example: "Hoy es lunes.", phonetic: "oy", tier: 4 },
  { id: 196, spanish: "mañana", english: "tomorrow / morning", pos: "noun", example: "Hasta mañana.", phonetic: "mah-NYAH-nah", tier: 4 },
  { id: 197, spanish: "ayer", english: "yesterday", pos: "adverb", example: "Ayer fue lunes.", phonetic: "ah-YEHR", tier: 4 },
  { id: 198, spanish: "siempre", english: "always", pos: "adverb", example: "Siempre feliz.", phonetic: "see-EHM-preh", tier: 4 },
  { id: 199, spanish: "nunca", english: "never", pos: "adverb", example: "Nunca digas nunca.", phonetic: "NOON-kah", tier: 4 },
  { id: 200, spanish: "gracias", english: "thank you", pos: "noun", example: "Muchas gracias.", phonetic: "GRAH-see-ahs", tier: 4 },
];

export function getWordsByTier(tier: number): Word[] {
  return vocabulary.filter(w => w.tier === tier);
}

export function getWordsByTiers(tiers: number[]): Word[] {
  return vocabulary.filter(w => tiers.includes(w.tier));
}
